version: 2

models:

    - name: sales
      description: this is a test of the descriptions, and a way to check that orders id - products id can be our PK
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: unique orders 
            tests : 
            - not_null 

          - name: products_id
            description: the different products contained here

          - name: qty
            description: amount of products ordered

          - name: turnover
            description: money made here

          - name: purchase_cost
            description: what it cost the company to acquire this good.

          - name: margin
            description: turnover - cogs

    - name: orders          
      columns:
          - name: orders_id
            description: unique orders 
            tests : 
            - not_null 
            - unique
